### ISSUE TITLE
Windows build when?

### ISSUE THREAD

**Issue by rayman3003** [captainys/TOWNSEMU#1]
When the windows build became available?

**Comment by captainys** [comment]
Hi,

I need to figure how to auto-build using GitHub (which I believe possible).  Binaries will be available as soon as I learn how to do it and I set up auto build.

Please give me some more time!

Thanks,

Soji

**Comment by rayman3003** [comment]
> I need to figure how to auto-build using GitHub (which I believe possible). Binaries will be available as soon as I learn how to do it and I set up auto build. Please give me some more time!

Thank u very much. Take ur time. Ill wait.

**Comment by captainys** [comment]
I have set up continuous integration that leaves the latest build as artifact.  Do you have access to:

https://github.com/captainys/TOWNSEMU/actions?query=workflow%3A%22Continuous+Integration%22

this link?  If you do, you should be able to click on the first workflow result from which you can download binaries.

I hope it works.  If it doesn't, I'll think about something else.

**Comment by rayman3003** [comment]
> 
> 
> I have set up continuous integration that leaves the latest build as artifact. Do you have access to:
> 
> https://github.com/captainys/TOWNSEMU/actions?query=workflow%3A%22Continuous+Integration%22
> 
> this link? If you do, you should be able to click on the first workflow result from which you can download binaries.
> 
> I hope it works. If it doesn't, I'll think about something else.

I grabbed a windows binary from there, But it looks like a CUI binary or something. Im looking for a GUI binary!

 Is it possible for u to add a GUI? something like this?

https://github.com/ocornut/imgui

**Comment by captainys** [comment]
OK.  I think this time you can download from:
https://github.com/captainys/TOWNSEMU/releases
I've added a GUI module.

**Comment by rayman3003** [comment]
> 
> 
> OK. I think this time you can download from:
> https://github.com/captainys/TOWNSEMU/releases
> I've added a GUI module.

Awesome, Thank u very much. It looks good. :D
