### ISSUE TITLE
ホストのマウスカーソルの消し方

### ISSUE THREAD

**Issue by nemimi2194** [captainys/TOWNSEMU#112]
日本語で大丈夫でしょうか？

ゲーム中、マウスカーソルが気になるので消し方を調べていたら
あっとチャンネルの書き込みを見つけまして

https://old.atchs.jp/Internet/51/162

48に山川機長さんの書き込みで
「Shift+Scroll Lockでホストのマウスカーソルをオン・オフできるようにしてみました」とあるのですができません。
キーが変わってしまったのか、機能を廃止にしてしまったでしょうか？

使用バージョン：v20231124
使用ROM：実機より吸い出したもの

**Comment by fuzz6001** [comment]
@nemimi2194
ちょっと調べてみましたが、今回のバージョン [v20231124](https://github.com/captainys/TOWNSEMU/releases/tag/v20231124) で動作しなくなってるようです。
[v20230913](https://github.com/captainys/TOWNSEMU/releases/tag/v20230913) まではちゃんとON/OFF出来るので、ひとまずこのバージョンを使ってみてはどうでしょうか？

**Comment by nemimi2194** [comment]
ありがとうございます！消せました！

**Comment by captainys** [comment]
直しました。ソースからビルドしていただけると最新版で直っていると思います。そうでない場合は、次回のリリースまでお待ちください。

ご報告ありがとうございました！
