### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by Solitair69** [captainys/TOWNSEMU#128]
Hi i stumbled upon the config
at least i think its the config 
Tsugaru_Default.Tsugaru
i saw the line 
APPSPEC 
could it be that this is the parameter for the aspect ratio?
still looking for a way to get tsugaru stretched to widescreen you know :D

**Comment by captainys** [comment]
No, it is application-specific augmentation, like controlling mouse-cursor position by joystick to fly Wing Commander or Strike Commander with a USB joystick.  So, are you looking for a way to expand the screen to the full Window size regardless of the aspect ratio?

**Comment by Solitair69** [comment]
Yea exactly ,:) but i Always use fullscreen No window

**Comment by captainys** [comment]
Are you able to build from the latest source?  I added free aspect ratio mode.  From CUI, use -FREEASPECT option, or from GUI check Auto Scaling, and uncheck Maintain Aspect Ratio.

**Comment by Solitair69** [comment]
ummm never built on my own so far

**Comment by Solitair69** [comment]
hmm tried to follow tutorials as good as i can but get cmake errors all the time dont know how this works :(

**Comment by Solitair69** [comment]
ok i made some progress :D

but getting these errors at the end

-- Building for: NMake Makefiles
CMake Error at CMakeLists.txt:3 (project):
  Running

   'nmake' '-?'

  failed with:

   no such file or directory


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by Solitair69** [comment]
hm ok i did it with cmake and then vs 2022 but thats confusing for me i thought there would be an output like when i download
tsugaru instead i have lots of stuff in many folders

**Comment by Solitair69** [comment]
Solved
