### ISSUE TITLE
Suspected page table cache pollution

### ISSUE THREAD

**Issue by nabe-abk** [captainys/TOWNSEMU#136]
Free386開発中に気付いたのですが、何かの条件でページテーブルキャッシュが正しくない値で汚染されている疑いがあります。

[この添付ファイル（free386_cr3.zip）](https://github.com/user-attachments/files/17083723/free386_cr3.zip) はFree386 Ver1.00の call_v86.asm にて CR3 のロードをコメントアウトしてビルドしたものです。CR3を書き換えるアプリは存在しないので、この状態ですと基本的にEXPプログラム起動中は CR3 の値がずっと固定されます。

非VCPI環境にて、添付のFree386を使用し、F-BASIC386 V2.1 L10を起動すると以下のように英字（半角）フォントの文字化が発生します。

![fb386](https://github.com/user-attachments/assets/04650beb-bbec-4065-833b-bf0c83a3d15e)

これは、全く同条件（同じHDDイメージを使用し同じように起動した）の「うんづ」では発生しません。よって導かれる結論としては、何かのタイミングでページキャッシュの汚染が起きているのではないかと思うのですが、さすがにTsugaruのソースからそれを追いかけるのは厳しかったので、ここに報告します。

- 知らない間にCR3が書き換わっている可能性は低いです。単純なコメントアウトではなく、CR3の現在の値と比較して値が書き換わっていたらロードするというコードにしても同じ現象が発生します。
- CR3のリロードコードは、他機種（PC/AT, PC-98）やうんづでは不要で、現状Tsugaruのためだけに存在するコードです。

**Comment by pinterior** [comment]
メモリ32MBに設定した津軽で少し動作を観察してみました。

1. `000c:0001cd9a` からリニア `8102402c` へのリードアクセスで `00169007` がキャッシュに入る
   - `rep movsd` で、DS は `64`
   - `0064:LiBase=81024000 Lim=00000FFF OpSz=20H AdSz=20H P=01 DPL=00 Type=13H @ PHYS:00077410H`
2. 後にリニア `81024348` を読んだ時に `fffc0007` を引きたいのにキャッシュされた `00169007` になっている
   - アイドル状態で `DUMP LDT` すると
     `0064:LiBase=81024000 Lim=0001AFFF OpSz=20H AdSz=20H P=01 DPL=00 Type=13H @ PHYS:00077410H`

また、以下のような挙動も観察されました:
- ベースアドレスは `000c:0005e216` あたりから LDT を直接変更している
- INT 21h AX=48h は常に EBX=0 で呼び出すものの、`BRKON INT 21 AX=250A` で停止することはない

ページテーブルもLDT同様直接変更しているものの、実機ではTLBエントリが十分少ない(486世代で32程度?)ので問題が起きていない…ということではないでしょうか。

**Comment by nabe-abk** [comment]
調査ありがとうございます。こちらでも引き続き調べてみました。結論から言うと F-BASIC386……どころか「SYSINITライブラリ」のバグでした。

mma_allocSeg() にて SYSINIT のメモリを割り当てて、mma_freeSeg() でセグメントを開放したとき、SYSINITライブラリ（T_OS.LIB内）は、セレクタ領域のページテーブルを自力で初期化（0クリア）しセレクタも開放しますが、**CR3をリロード（ページキャッシュクリア）をしていません……。**

pinteriorさんご指摘のとおり、これが無制限ページキャッシュと相まって不具合を起こしているようです。


余談ですが、CoCoやGSTART、TBIOS等々、TOWNSのシステム系ソフトは、int 21/AH=48h のセレクタ確保だけDOS-Extenderコールを使用し、あとはなぜか自力でページテーブルやLDTを書き換えることが好きなようです。どういう設計してるんだ？　という話で……。

※GSTART.EXPはEXGアプリのメモリ管理をしているので仕方ないのですが……。

**Comment by pinterior** [comment]
> あとはなぜか自力でページテーブルやLDTを書き換えることが好きなようです。どういう設計してるんだ？　という話で……。

- DOS|Extenderシステムコールではどのようなリニアアドレスを使用するか関与できず、INT 21h AX=250ah は新たなページテーブルの割り当てが必要になった際にリアルモードメモリが残っていないと失敗してしまう
- minreal をリンク時に設定すればよいが、ただでさえ貴重なメモリが

という状況で、VRAMまわりのリニアアドレスが物理アドレスに寄せてあるならばスプライトRAMに対応するページテーブルに空きが多いはずなのでリサイクルしたかった、というのは考えすぎでしょうか 🤔

**Comment by nabe-abk** [comment]
> DOS|Extenderシステムコールではどのようなリニアアドレスを使用するか関与できず、INT 21h AX=250ah は新たなページテーブルの割り当てが必要になった際にリアルモードメモリが残っていないと失敗してしまう

RUN386のページテーブルはリアルモードメモリ限定ではなく、空きメモリ（ページ）があればマッピングは成功します。ただ TOWNS のプログラム多くは `-maxdata 0ffffffffh`（デフォルト）になっているので、基本的に空きメモリはありません。

なので、SYSINITライブラリは初期化タイミングもEXP起動後でどうにもできませんし、ページテーブルが存在しかつ空いている空間（`8102_0000h-813f_ffffh`）を使いたかったのはありそうですね。

それにしても他は……ですが。
