### ISSUE TITLE
NextVSYNCTime does not always return greater value than parameter

### ISSUE THREAD

**Issue by pinterior** [captainys/TOWNSEMU#17]
https://github.com/captainys/TOWNSEMU/blob/b31d47286102e1731188ef7c366cd6999097926c/src/towns/crtc/crtc.h#L314-L316
https://github.com/captainys/TOWNSEMU/blob/b31d47286102e1731188ef7c366cd6999097926c/src/towns/crtc/crtc.h#L325-L331

If `CRT_VERTICAL_DURATION <= townsTime % VSYNC_CYCLE`, the return value will be less than or equal to given `townsTime`.
Is this an expected behavior?

**Comment by captainys** [comment]
No, it's not intended.  I'm going to merge it if you submit a pull-request.  Thank you for finding it!

**Comment by pinterior** [comment]
I'll make a change on PR for double-buffered sprite. (for program watching `PAGE` bit on `044ch`)
