### ISSUE TITLE
Reference not defined to YsSoundPlayer

### ISSUE THREAD

**Issue by ryugold777** [captainys/TOWNSEMU#19]
There is an issue when run "make".

yssimplesound.cpp:(.text+0x843): reference not defined to "YsSoundPlayer::SoundData::DeleteAPISpecificData(YsSoundPlayer::SoundData::APISpecificDataPerSoundData*)"
../externals/yssimplesound/src/libyssimplesound.a(yssimplesound.cpp.o): Na função "YsSoundPlayer::SoundData::CleanUp()":
yssimplesound.cpp:(.text+0x896): referência não definida para "YsSoundPlayer::SoundData::CleanUpAPISpecific()"
collect2: error: ld returned 1 exit status
tests/CMakeFiles/disasm_addr.dir/build.make:161: recipe for target 'tests/disasm_addr' failed
make[2]: *** [tests/disasm_addr] Error 1
CMakeFiles/Makefile2:2616: recipe for target 'tests/CMakeFiles/disasm_addr.dir/all' failed
make[1]: *** [tests/CMakeFiles/disasm_addr.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by captainys** [comment]
Can you tell me in what environment you are compiling?

**Comment by ryugold777** [comment]
I tried to compile in "Bodhi linux" and after on "lubuntu". Receveid the same error.

**Comment by captainys** [comment]
Actually, can you check a line 6 in src/tests/CMakeLists.txt?  Does it have yssimplesound_nownd in that line?  The line should look like:

target_link_libraries(disasm_addr towns yssimplesound_nownd)

**Comment by ryugold777** [comment]
> Actually, can you check a line 6 in src/tests/CMakeLists.txt? Does it have yssimplesound_nownd in that line? The line should look like:
> 
> target_link_libraries(disasm_addr towns yssimplesound_nownd)

yes this line exists!
`target_link_libraries(disasm_addr towns yssimplesound_nownd)`

**Comment by captainys** [comment]
OK,  I think I fixed it.  UNIX linker (ld) stubbornly does on-path linking.  That was why you were getting an error.  Programmers have been suffering, and nobody seems to be interested in fixing it.

**Comment by ryugold777** [comment]
yes now  works but when I try to "cmake --build main_gui it says "error: could not load cache" when I'm inside the folder /gui/src and even outside return "$ cmake --build main_gui
Error: /home/rafa/TOWNSEMU/src/public/build/main_gui is not a directory"

**Comment by ryugold777** [comment]
Thanks captainys now work on linux! I builded on bodhi linux following instructions from arch. Thanks again!

**Comment by captainys** [comment]
OK.  I'm glad you made it work!
