### ISSUE TITLE
Support for .mds, .mdf

### ISSUE THREAD

**Issue by mcfilmmakers** [captainys/TOWNSEMU#21]
Please support these other very common file types!

**Comment by captainys** [comment]
I know those data format exist, but is there an official file format specification anywhere?  If there is, and if it is easy enough, I can try supporting it.

**Comment by ShriveledSquirrel** [comment]
I second this :(.

Also, I assume there isn't anything that I can do as I haven't programmed anything in years, but is there anything that people can do to help you? Like, finding you another machine to tinker with or something. Just curious.

**Comment by fuzz6001** [comment]
Documentation by nocash author
https://problemkaputt.de/psx-spx.htm#cdromdiskimagesmdsmdfalcohol120

**Comment by captainys** [comment]
OK.  That's cool.  Let me look into it.  Thanks!

**Comment by captainys** [comment]
Are you able to compile?  I've added support for MDS/MDF.  Looks to be working on my environment, but I have only tested with a few images.

**Comment by captainys** [comment]
MDS/MDF support is stable now.  Issue resolved.
