### ISSUE TITLE
Is it possible to change disk while emulator is running?

### ISSUE THREAD

**Issue by mcfilmmakers** [captainys/TOWNSEMU#27]
I am wondering if there is a way to change the floppy disk while the emulator is running. Some games require multiple floppy disks such as Asuka 120% Burning Fest which has 3 disks). I can boot with disk a and disc B but then it asks to put disk c in drive 0 and I see no way of doing that...

**Comment by pinterior** [comment]
FD0LOAD or FD1LOAD command may work.

> FD0LOAD filename
> FD1LOAD filename
>   Load FD image.  The number 0 or 1 is the drive number.
