### ISSUE TITLE
CUI issue with game paths containing folder names with spaces?

### ISSUE THREAD

**Issue by PanosPl** [captainys/TOWNSEMU#41]

**Comment by captainys** [comment]
Ah, I think that's highly possible.  I fixed some locations, but I'm not surprised this issue remains somewhere.  Can you be specific about what path is it?  CD-image?  FD-image?  From command?  Or from GUI?  Also the program does not support non-ASCII letters unless the file-system encoding is UTF8.  Linux and macOS by default UTF8, but Windows may have this issue.

**Comment by PanosPl** [comment]
Thank you for your reply. Using / instead of \ and putting the names into quotes seem to solve the issue! In other was, there was no issue at all :)

**Comment by captainys** [comment]
Oh, yes.  Double-quote is necessary for a file name with spaces.  I'm glad the problem has been solved!
