### ISSUE TITLE
Corrupt image in Alshark's opening

### ISSUE THREAD

**Issue by Mistranger** [captainys/TOWNSEMU#58]
The opening scene in FM Towns version of Alshark doesn't fit on screen properly, it appears to be enlarged and half of image is cut from the right side:
![tsugaru](https://user-images.githubusercontent.com/10031125/199282943-d7b1d560-4983-4929-91e4-1b461f513ad2.PNG)

Unz seems to shift the image a bit to left, but everything fits to screen:
![unz](https://user-images.githubusercontent.com/10031125/199283651-32815e04-4efb-4fa1-835e-0cd22747676b.PNG)

Note that this affect the opening scene only. The actual gameplay part works fine, the only issue is the opening scene.

**Comment by captainys** [comment]
Thank you for finding it.  This CRTC settings is rarely used, and I still do not fully understand how I should interpret it, but I made an ad-hoc fix.  It should take care of known cases.  Are you able to build your own?  I've just pushed the source but haven't made a release yet.

**Comment by Mistranger** [comment]
Thanks, now everything seems to be in order:
![изображение](https://user-images.githubusercontent.com/10031125/225019318-9072785a-47df-4653-927b-71387bcdc271.png)
