### ISSUE TITLE
Wizardry 5 causes a "Reason:Not all sector data was transferred by DMA (Mem->FD)" error

### ISSUE THREAD

**Issue by davemoore22** [captainys/TOWNSEMU#64]
Hello,

so I'm running Tsugaru on Linux (Ubuntu 22 - thank you for the precompiled binary).  I'm trying to run Wizardry V with the GUI. I have put the ISO file into CD, and I create a blank floppy (1.2 MB) and put it into FD0. For Wizardry V you need to create a scenario disk before playing, so I try that option, and there is a Japanese error message which translates to something like unable to format a scenario disk (see screenshot). 

![image](https://user-images.githubusercontent.com/48893555/213887249-cad826fc-508c-474c-a568-1333a56f25d8.png)

But I also get this error:

```
VM Aborted!
Device:FDC
Reason:Not all sector data was transferred by DMA (Mem->FD).
Towns TIME (Nano-Seconds): 126014439429
CS:EIP=0262:0000088F  LINEAR:00002EAF  EFLAGS=00000212  CPL=00
EAX=00000002  EBX=00000080  ECX=000C0D47  EDX=0000012C
ESI=00000466  EDI=000004C1  EBP=00000B8C  ESP=00000B80
CS=0262(LIN:00002620)  DS=07AF(LIN:00007AF0)  ES=0000(LIN:00000000)  
FS=0000(LIN:00000000)  GS=0000(LIN:00000000)  SS=0988(LIN:00009880)  
CR0=00000000  CR1=00000000  CR2=00000000  CR3=00000001
CF0  PF0  AF1  ZF0  SF0  TF0  IF1  DF0  OF0  IOPL00  NT0  RF0  VM0  AC0
Default Operand Size=16  Default Address Size=16  Stack Address Size=16
SS+00000000:1A 06 4A 03 F1 00 C0 00 62 02 56 00 86 00 20 06 
SS+00000010:02 00 01 00 01 00 16 8E 01 00 0C 00 E2 5E 00 00 
0262:0000088F 7418                      JE      000008A9
```

And I can't proceed any further.

**Comment by captainys** [comment]
Thank you for reporting it!  I've confirmed the DMA failure. I'll look into it.

**Comment by captainys** [comment]
I've confirmed it was a media-type identification issue.  I think I fixed it.  Are you able to build from the source?  I can at least start the game with the one I've just pushed.  By the way, since Wizardry 5 uses a 256 bytes per sector format, .BIN format does not work.  You need to use .D77 disk image.

**Comment by davemoore22** [comment]
Yes, I'll rebuild from source this evening and try again. Thank you!

**Comment by davemoore22** [comment]
I can confirm that worked, thank you! Scenario Disk (a D77 disk image) written successfully.

![image](https://user-images.githubusercontent.com/48893555/214090890-1534e133-dbee-4f29-9dba-71f2ba8cf72d.png)

Thank you so much.

**Comment by davemoore22** [comment]
Oh, spoke a bit too soon. It can *write* and create a Scenario Disk from a blank d77 format 1.2 disk image, and using that the game can start, but if you restart the VM and start Wizardry 5 again, the Scenario Disk you've just created is unreadable.

I've uploaded the Scenario Disk I created here:

https://tempfile.io/en/VkJtb1PLSFTPRxQ/file

**Comment by davemoore22** [comment]
Yes, it did! thank you.

Incidentally, on the command line version, what's the key press to open the Console?

**Comment by captainys** [comment]
Sure.  Thank you for using Tsugaru and preserving the heritage of FM TOWNS!
