### ISSUE TITLE
HIMEM.SYS form MS-DOS 6.2 L10 fails to initialize XMS

### ISSUE THREAD

**Issue by jckarter** [captainys/TOWNSEMU#88]
Hi! I was trying to install MS-DOS and Windows 3.1 under Tsugaru. When I try to boot DOS, HIMEM.SYS raises an error about not being able to use high memory, and then EMM386.EXE also fails, and WINSETUP.EXE refuses to start because XMS isn't available. Here's a screenshot:

<img width="672" alt="Screenshot 2023-06-16 at 7 40 11 PM" src="https://github.com/captainys/TOWNSEMU/assets/147281/e313ffbe-f23f-4b67-852e-170447dde33a">

I've tried the free compatible ROMs as well as real ROMs, and tried with high-fidelity CPU enabled and disabled. Is there something else I need to do to successfully boot DOS and Windows?

**Comment by pinterior** [comment]
it's not Tsugaru specific problem.
please use `SETUP2.EXE` in DOS directory to configure HMA/EMS settings.

- select memory icon
![image](https://github.com/captainys/TOWNSEMU/assets/6851003/c2dd31f5-8202-4c93-940a-5653fc06c2ad)

- the setting should be something like:
![image](https://github.com/captainys/TOWNSEMU/assets/6851003/67025f70-32a2-46de-a9e5-61768379d24c)

**Comment by jckarter** [comment]
Ah, thank you!
