### ISSUE TITLE
Mahou Daisakusen freezes when pausing

### ISSUE THREAD

**Issue by ualaa1** [captainys/TOWNSEMU#95]
I set game port 0 to game pad by host keyboard. After the loading screen and intro, press S, then A. Then select ship with arrows and x keys. Go past dialogue with the x key. Press S key to pause the game. Game then freezes. On the bottom GUI, the CD icon keeps flashing.

Game needs to unpause when pressing the S key after pausing

**Comment by captainys** [comment]
The problem was CDDA status was not put back to PLAYING after CDDA RESUME command.  I've pushed the source with a fix.

Thank you for finding it!
